### ISSUE TITLE
Reuse GPU build on CPU

### ISSUE THREAD

**Issue by jakirkham** [conda-forge/ucx-split-feedstock#66]
Given how UCX is architected (using `dlopen` for communication protocol backends), it may make sense to build GPU support even in the CPU only case and simply make `cudatoolkit` an optional requirement. This way if `cudatoolkit` is not installed, the GPU parts are simply not used. So it would work just as well when a GPU is not available.

Though one thing we still need to check is how UCX behaves when built under different CUDA versions.

**Comment by leofang** [comment]
This is what we do in openmpi-feedstock. Open MPI also uses `dlopen` to dynamically link to `libcuda.so`. There we don't even need to worry about the impact of different CUDA versions at build time, as inspecting the Open MPI codebase shows it does not matter after CUDA 8 (?) onward, so we just picked the lowest version supported by conda-forge, which is 9.2. In general I think this is the right direction to go.

**Comment by jakirkham** [comment]
Yeah that was part of the motivation behind this issue.

That said, it's not quite that simple (though close). More relevant info in issue ( https://github.com/openucx/ucx/issues/4762 ).

**Comment by leofang** [comment]
Ah...I see. I wish life is simpler!

**Comment by jakirkham** [comment]
To clarify there are some optimizations used starting with CUDA 10.0 ( https://github.com/openucx/ucx/issues/4762#issuecomment-586407115 ). Though I think now that we are using CUDA 10.2+ in conda-forge, this may be less of an issue

**Comment by jakirkham** [comment]
cc @pentschev (in case you know more here; am now recalling some CUDA 11 changes)

**Comment by pentschev** [comment]
I can't say with 100% certainty, but it seems like the only version specific CUDA checks are testing for CUDA >= 10.0, specifically to enable usage of [cuLaunchHostFunc](https://docs.nvidia.com/cuda/cuda-driver-api/group__CUDA__EXEC.html#group__CUDA__EXEC_1gab95a78143bae7f21eebb978f91e7f3f) in https://github.com/openucx/ucx/blob/2823e3aa7a023de5128c5cb829ee9e4e566cc6b3/src/uct/cuda/cuda_ipc/cuda_ipc_iface.c#L223-L228 , https://github.com/openucx/ucx/blob/2823e3aa7a023de5128c5cb829ee9e4e566cc6b3/src/uct/cuda/cuda_ipc/cuda_ipc_iface.c#L323-L330 , https://github.com/openucx/ucx/blob/2823e3aa7a023de5128c5cb829ee9e4e566cc6b3/src/uct/cuda/cuda_copy/cuda_copy_iface.c#L190-L195 , https://github.com/openucx/ucx/blob/2823e3aa7a023de5128c5cb829ee9e4e566cc6b3/src/uct/cuda/cuda_copy/cuda_copy_iface.c#L222-L228 .

It seems to still be consistent with https://github.com/openucx/ucx/issues/4762#issuecomment-586407115 , so as long as we make sure we support only CUDA >= 10.0, we should be ok with that.

**Comment by leofang** [comment]
Currently Open MPI supports CUDA 9.2+ and I'd prefer to not mess up with that unless absolutely necessary. From Open MPI's perspective it doesn't care about the CUDA version. Maybe we'll need to release two versions on linux64, one with CUDA 9.2 and no UCX support, and the other is CUDA 10.0+ with (optional) UCX support.

**Comment by jakirkham** [comment]
One option might be to build CUDA 9.2 and 10.0 flavors of UCX

Though it's worth noting we did drop CUDA versions prior to 10.2 in conda-forge when adding newer CUDA 11 versions ( https://github.com/conda-forge/conda-forge-pinning-feedstock/pull/1162 )

**Comment by leofang** [comment]
Right, but as long as the docker images are still present, a feedstock maintainer is free to choose supporting CUDA 9.2-10.1 by setting up a `conda_build_config.yaml` (like what we did in CuPy).

**Comment by leofang** [comment]
Sorry @jakirkham @pentschev I swear I clicked send but apparently my question was not posted.

If `ucx` is built with CUDA version X, can we run it with CUDA version Y != X? If so the problem is solved for Open MPI.

**Comment by pentschev** [comment]
As per https://github.com/conda-forge/ucx-split-feedstock/issues/66#issuecomment-813944211, my understanding is yes if build and runtime are both >= 10.0 or both < 10.0, I don't see any other conditions that invalidate that.

**Comment by jakirkham** [comment]
Would propose we make this change with `1.14.0`. In particular `cudatoolkit` will move from a `run` dependency to `run_constrained` (optional)

**Comment by jakirkham** [comment]
Looking at UCX recently ( https://github.com/openucx/ucx/issues/4762#issuecomment-1433720708 ), it appears this has gotten trickier. Perhaps another approach would be to split out the CUDA components into a separate optional package

Open to other ideas as well

**Comment by kkraus14** [comment]
All the code I see in that issue seems to guard against allowing a build with newer CUDA version to continue running successfully on older CUDA versions. It also looks like only the cuda driver and cuda runtime are used.

It looks like we could build a single package with say CUDA 11.8 and depend on UCX to handle the case where we're running on an older CUDA driver version (I'm unclear if we'd want to statically link the CUDA runtime here).

In that case the extra package size from building the CUDA pieces and static linking the cuda runtime would be negligible.
